name: ROS2 build test

env:
  # cache directory for docker image
  PATH_CACHE: /tmp/docker-img-arch
  PATH_MOUNT: /workspaces/docker-mount

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04

    container: ros:humble-ros-base
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install apt repository
        run: |
            apt-get update
            apt-get install -y libzmq3-dev libboost-dev qtbase5-dev libqt5svg5-dev libzmq3-dev libdw-dev