name: ROS2 build test

env:
  # cache directory for docker image
  PATH_CACHE: /tmp/docker-img-arch
  PATH_MOUNT: /workspaces/docker-mount

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04

    container: ros:humble-ros-base
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install apt repository
        run: |
            sudo apt-get update
            sudo apt-get install -y libzmq3-dev libboost-dev qtbase5-dev libqt5svg5-dev libzmq3-dev libdw-dev

      - name: Behaivor Tree cache restore
        id: cache-behaivor-tree
        uses: actions/cache@v4
        with:
            path: ./BehaviorTree.CPP
            key: ${{ runner.os }}-build-behaivor-tree-${{ hashFiles('**/package-lock.json')}}
            restore-keys:
                ${{ runner.os }}-build-behaivor-tree-

      - if: ${{ steps.cache-behaivor-tree.outputs.cache-hit != 'true' }}
        name: Build Behaivor Tree
        run: |
            git clone https://github.com/BehaviorTree/BehaviorTree.CPP.git
            cd BehaviorTree.CPP
            git checkout tags/4.7.0
            mkdir build
            cd build
            cmake ..
            make -j8

      - name: Install behaivor tree
        run:  |
            cd BehaviorTree.CPP
            sudo make install