name: ROS2 build test

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: package test

    strategy:
      matrix:
        os:
          - ubuntu-22.04
        rosdistro:
          - humble

    runs-on: ubuntu-22.04

    container:
      image: ros:${{ matrix.rosdistro }}-ros-base

    steps:
      - name: Setup directories
        run: mkdir -p ros2_ws/src
      

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: ros2_ws/src/yasarobo2025_26
    #   - name: Cache Behaivor tree exe
    #     uses: actions/cache@v4
    #     with: 
    #       path: |
    #         /usr/local/include/behaviortree_cpp
    #         /usr/local/lib/libbehaviortree_cpp*
    #       key: ${{ runner.os }}-${{ github.ref_name }}-btcpp-4.7.0


      - name: Checkout code
        uses: actions/checkout@v4
        with: 
            path: ros_ws/src
