name: ROS2 build test

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: package test
    runs-on: ubuntu-22.04

    steps:
      - name: Create ros2 workspace
        run: mkdir -p ros_ws/src

      - name: Cache APT packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ github.ref_name }}-${{ hashFiles('**/apt-packages.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-${{ github.ref_name }}

      - name: Cache Behaivor tree exe
        uses: actions/cache@v4
        with: 
          path: |
            /usr/local/include/behaviortree_cpp
            /usr/local/lib/libbehaviortree_cpp*
          key: ${{ runner.os }}-${{ github.ref_name }}-btcpp-4.7.0


      - name: Checkout code
        uses: actions/checkout@v4
        with: 
            path: ros_ws/src
    
      - name: ROS2 Humble setup
        run: |
            sudo apt install software-properties-common
            sudo add-apt-repository universe
            sudo apt update && sudo apt install curl -y
            export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}')
            curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo ${UBUNTU_CODENAME:-${VERSION_CODENAME}})_all.deb"
            sudo dpkg -i /tmp/ros2-apt-source.deb
            sudo apt update
            sudo apt upgrade
            sudo apt install ros-humble-desktop
            source /opt/ros/humble/setup.bash

      - name: rosdep setup
        run: |
            sudo apt-get install python3-rosdep
            sudo rosdep init
            rosdep update

      - name: Install colcon
        run: |
            sudo apt install -y python3-colcon-common-extensions

      - name: Install BaheaivorTree
        run: |
            sudo apt install libzmq3-dev libboost-dev qtbase5-dev libqt5svg5-dev libzmq3-dev libdw-dev
            git clone https://github.com/BehaviorTree/BehaviorTree.CPP.git
            cd BehaviorTree.CPP
            git checkout tags/4.7.0
            mkdir build
            cd build
            cmake ..
            make -j8
            sudo make install

      - name: Install gazebo
        run: |
            sudo apt -y install gazebo
            sudo apt install ros-humble-gazebo-*
            . /usr/share/gazebo/setup.sh

      - name: Install lidar packages
        run: |
            sudo apt install libudev-dev
            sudo apt install libopencv-dev
            cd ros_ws/src
            git clone git@github.com:keigo1216/ldrobot-lidar-ros2.git
            cd ldrobot-lidar-ros2
            git checkout humble
            cd scripts
            ./create_udev_rules.sh

      - name: Install inrof2025_ros_type
        run: |
            cd ros_ws/src
            git clone git@github.com:keigo1216/inrof2025_ros_type.git
            cd inrof2025_ros_type
            colcon build --packages-select inrof2025_ros_type